2024-03-29 15:19:04.404 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-29 15:19:04.408 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-29 15:19:08.655 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2024-03-29 15:19:08.703 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=16 from 2024-03-15 19:07:27.277934)
2024-03-29 15:19:19.606 WARNING (MainThread) [homeassistant.setup] Setup of bluetooth is taking over 10 seconds.
2024-03-29 15:19:32.356 ERROR (Thread-2) [pychromecast.discovery] Unhandled exception in worker thread
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pychromecast/discovery.py", line 302, in run
    self._poll_hosts()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/discovery.py", line 328, in _poll_hosts
    device_status = get_device_info(host, timeout=30, context=self._context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychromecast/dial.py", line 184, in get_device_info
    _, status = _get_status(
                ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychromecast/dial.py", line 95, in _get_status
    with urllib.request.urlopen(req, timeout=timeout, context=context) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 1313, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1451, in __init__
    super(HTTPSConnection, self).__init__(host, port, timeout,
  File "/usr/local/lib/python3.12/http/client.py", line 878, in __init__
    self._validate_host(self.host)
  File "/usr/local/lib/python3.12/http/client.py", line 1280, in _validate_host
    raise InvalidURL(f"URL can't contain control characters. {host!r} "
http.client.InvalidURL: URL can't contain control characters. 'Lex Fridman' (found at least ' ')
2024-03-29 15:19:32.378 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/discovery.py", line 302, in run
    self._poll_hosts()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/discovery.py", line 328, in _poll_hosts
    device_status = get_device_info(host, timeout=30, context=self._context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychromecast/dial.py", line 184, in get_device_info
    _, status = _get_status(
                ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychromecast/dial.py", line 95, in _get_status
    with urllib.request.urlopen(req, timeout=timeout, context=context) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 1313, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1451, in __init__
    super(HTTPSConnection, self).__init__(host, port, timeout,
  File "/usr/local/lib/python3.12/http/client.py", line 878, in __init__
    self._validate_host(self.host)
  File "/usr/local/lib/python3.12/http/client.py", line 1280, in _validate_host
    raise InvalidURL(f"URL can't contain control characters. {host!r} "
http.client.InvalidURL: URL can't contain control characters. 'Lex Fridman' (found at least ' ')
2024-03-29 15:19:45.899 ERROR (MainThread) [homeassistant.components.homeassistant_alerts] Error requesting homeassistant_alerts data: Cannot connect to host alerts.home-assistant.io:443 ssl:default [Try again]
2024-03-29 15:19:50.985 ERROR (MainThread) [custom_components.hacs] Could not update template - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Try again]
2024-03-29 15:19:50.985 ERROR (MainThread) [custom_components.hacs] Could not update integration - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Try again]
2024-03-29 15:19:50.986 ERROR (MainThread) [custom_components.hacs] Could not update plugin - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Try again]
2024-03-29 15:19:50.986 ERROR (MainThread) [custom_components.hacs] Could not update theme - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Try again]
2024-03-29 15:24:13.123 ERROR (MainThread) [homeassistant.components.upnp] Error fetching TL-WR841N data: Unable to communicate with IGD at: http://192.168.0.1:1900/gatedesc.xml
2024-03-29 15:24:58.327 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:25:28.329 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:25:58.331 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:26:28.334 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:26:58.336 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:27:28.340 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:27:58.342 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:28:28.345 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:28:58.349 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:29:02.817 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=19 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=19, family=2, type=2, proto=0, laddr=('0.0.0.0', 51465)>
2024-03-29 15:29:28.351 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:29:58.354 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:29:58.355 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 15:34:33.266 ERROR (MainThread) [homeassistant.components.analytics] Error sending analytics to https://analytics-api.home-assistant.io/v1: ClientConnectorError(ConnectionKey(host='analytics-api.home-assistant.io', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=1438284371841560115), gaierror(-3, 'Try again'))
2024-03-29 15:35:16.206 ERROR (MainThread) [homeassistant.components.upnp] Error fetching TL-WR841N data: Unable to communicate with IGD at: http://192.168.0.1:1900/gatedesc.xml
2024-03-29 15:40:16.802 ERROR (MainThread) [homeassistant.components.upnp] Error fetching TL-WR841N data: Unable to communicate with IGD at: http://192.168.0.1:1900/gatedesc.xml
2024-03-29 15:40:28.388 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:40:28.390 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 15:40:58.390 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:40:58.392 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 15:44:28.403 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:44:28.405 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 15:45:14.819 ERROR (MainThread) [homeassistant.components.upnp] Error fetching TL-WR841N data: Unable to communicate with IGD at: http://192.168.0.1:1900/gatedesc.xml
2024-03-29 15:45:28.411 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:45:28.413 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 15:45:58.417 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:45:58.419 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 15:46:28.422 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:46:28.424 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 15:46:58.427 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:46:58.428 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 15:47:28.429 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 15:47:28.431 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 15:48:23.811 ERROR (MainThread) [homeassistant.components.upnp] Error fetching TL-WR841N data: Unable to communicate with IGD at: http://192.168.0.1:1900/gatedesc.xml
2024-03-29 16:02:23.841 WARNING (DHCPWatcher) [scapy.runtime] Socket <scapy.arch.linux.L2ListenSocket object at 0x7fa4548c8230> failed with '[Errno 100] Network is down'. It was closed.
2024-03-29 16:02:28.511 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:02:28.513 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:02:43.232 ERROR (MainThread) [homeassistant.components.upnp] Error fetching TL-WR841N data: Unable to communicate with IGD at: http://192.168.0.1:1900/gatedesc.xml
2024-03-29 16:02:58.514 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:02:58.515 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:03:28.516 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:03:28.517 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:03:58.519 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:03:58.521 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:04:28.523 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:04:28.525 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:04:58.526 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:04:58.527 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:05:28.528 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:05:28.529 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:05:58.530 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:05:58.531 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:06:28.532 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:06:28.534 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:06:58.535 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:06:58.538 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:07:28.539 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:07:28.542 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:07:57.346 ERROR (MainThread) [homeassistant.components.upnp] Error fetching TL-WR841N data: Unable to communicate with IGD at: http://192.168.0.1:1900/gatedesc.xml
2024-03-29 16:07:58.543 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:07:58.545 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:08:28.546 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:08:28.548 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:08:58.549 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:08:58.550 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:09:02.823 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=19 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=19, family=2, type=2, proto=0, laddr=('0.0.0.0', 51465)>
2024-03-29 16:09:02.824 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=10, type=2, proto=0, laddr=('::', 48763, 0, 0)>
2024-03-29 16:09:28.551 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:09:28.553 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:09:58.555 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:09:58.557 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:10:28.558 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:10:28.561 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:10:58.563 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:10:58.566 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:11:28.566 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:11:28.569 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:11:58.568 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:11:58.572 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:12:28.571 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:12:28.574 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:12:58.574 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:12:58.576 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:13:28.577 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:13:28.579 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:13:58.579 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:13:58.582 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:14:28.581 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:14:28.584 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:14:58.585 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:14:58.587 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:15:18.022 WARNING (MainThread) [zeroconf] Error with socket 14 (('192.168.0.108', 5353))): [Errno 101] Network unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1261, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 101] Network unreachable
2024-03-29 16:15:18.034 WARNING (MainThread) [zeroconf] Error with socket 15 (('fe80::c033:90c6:4d7c:29f4', 5353, 0, 4))): [Errno 101] Network unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1261, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 101] Network unreachable
2024-03-29 16:15:28.588 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:15:28.590 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:15:58.590 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:15:58.592 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:16:28.594 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:16:28.594 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:16:58.595 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:16:58.597 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:17:28.598 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:17:28.599 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:17:58.601 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:17:58.603 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:18:08.835 ERROR (MainThread) [homeassistant.components.upnp] Error fetching TL-WR841N data: Unable to communicate with IGD at: http://192.168.0.1:1900/gatedesc.xml
2024-03-29 16:18:28.603 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:18:28.606 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:18:58.607 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:18:58.609 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:19:02.825 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=19 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=19, family=2, type=2, proto=0, laddr=('0.0.0.0', 51465)>
2024-03-29 16:19:02.826 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=10, type=2, proto=0, laddr=('::', 48763, 0, 0)>
2024-03-29 16:19:28.610 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:19:28.612 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:19:58.613 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:19:58.615 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:20:26.853 ERROR (MainThread) [homeassistant.components.upnp] Error fetching TL-WR841N data: Unable to communicate with IGD at: http://192.168.0.1:1900/gatedesc.xml
2024-03-29 16:20:28.617 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:20:28.618 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:20:58.621 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:20:58.622 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:21:28.624 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:21:28.625 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:21:58.627 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:21:58.628 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:22:28.629 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:22:28.631 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:22:37.827 ERROR (MainThread) [homeassistant.components.upnp] Error fetching TL-WR841N data: Unable to communicate with IGD at: http://192.168.0.1:1900/gatedesc.xml
2024-03-29 16:22:58.631 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:22:58.634 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:23:28.636 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:23:28.638 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:23:58.640 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:23:58.641 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:24:28.642 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:24:28.644 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:24:58.646 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 19] No such device, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:24:58.648 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:25:28.650 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:25:28.651 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:25:58.651 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:25:58.677 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:26:26.205 ERROR (MainThread) [homeassistant.components.upnp] Error fetching TL-WR841N data: Unable to communicate with IGD at: http://192.168.0.1:1900/gatedesc.xml
2024-03-29 16:26:28.676 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:26:28.679 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:26:58.678 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:26:58.681 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:27:28.682 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:27:28.683 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:27:58.685 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:27:58.686 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:28:28.688 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:28:28.690 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:28:58.692 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:28:58.694 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:29:02.826 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=19 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=19, family=2, type=2, proto=0, laddr=('0.0.0.0', 51465)>
2024-03-29 16:29:02.828 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=10, type=2, proto=0, laddr=('::', 48763, 0, 0)>
2024-03-29 16:29:28.695 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:29:28.698 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:29:58.701 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:29:58.702 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:30:28.704 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:30:28.707 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:30:58.709 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:30:58.710 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:31:28.711 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:31:28.713 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:31:58.715 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:31:58.717 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:32:28.717 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:32:28.720 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:32:58.720 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:32:58.724 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:33:28.725 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:33:28.726 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:33:58.728 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:33:58.731 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:34:28.733 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:34:28.742 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:34:58.775 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:34:58.785 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:35:28.788 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:35:28.796 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:35:58.797 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:35:58.800 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:36:28.837 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:36:28.853 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:36:58.854 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:36:58.867 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:37:28.866 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:37:28.870 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:37:58.870 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:37:58.910 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:38:28.874 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:38:28.912 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:38:58.877 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:38:58.917 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:39:02.859 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=19 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=19, family=2, type=2, proto=0, laddr=('0.0.0.0', 51465)>
2024-03-29 16:39:02.860 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=10, type=2, proto=0, laddr=('::', 48763, 0, 0)>
2024-03-29 16:39:28.881 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:39:28.920 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:39:58.885 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:39:58.922 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:40:28.889 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:40:28.924 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:40:58.893 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:40:58.927 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:41:28.898 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:41:28.930 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:41:58.901 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:41:58.932 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:42:28.906 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:42:28.934 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:42:58.910 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:42:58.937 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:43:28.914 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:43:28.939 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:43:58.918 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:43:58.950 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:44:28.920 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:44:28.952 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:44:58.922 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:44:58.955 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:45:28.925 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:45:28.958 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
2024-03-29 16:45:58.928 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=29 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=29, family=2, type=2, proto=0, laddr=('0.0.0.0', 46566)>
2024-03-29 16:45:58.960 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=33 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=33, family=10, type=2, proto=0, laddr=('::', 33075, 0, 0)>
