2024-03-31 17:44:07.321 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-31 17:44:07.323 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-31 17:44:22.654 ERROR (Thread-2) [pychromecast.discovery] Unhandled exception in worker thread
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pychromecast/discovery.py", line 302, in run
    self._poll_hosts()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/discovery.py", line 328, in _poll_hosts
    device_status = get_device_info(host, timeout=30, context=self._context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychromecast/dial.py", line 184, in get_device_info
    _, status = _get_status(
                ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychromecast/dial.py", line 95, in _get_status
    with urllib.request.urlopen(req, timeout=timeout, context=context) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 1313, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1451, in __init__
    super(HTTPSConnection, self).__init__(host, port, timeout,
  File "/usr/local/lib/python3.12/http/client.py", line 878, in __init__
    self._validate_host(self.host)
  File "/usr/local/lib/python3.12/http/client.py", line 1280, in _validate_host
    raise InvalidURL(f"URL can't contain control characters. {host!r} "
http.client.InvalidURL: URL can't contain control characters. 'Lex Fridman' (found at least ' ')
2024-03-31 17:44:22.689 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/discovery.py", line 302, in run
    self._poll_hosts()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/discovery.py", line 328, in _poll_hosts
    device_status = get_device_info(host, timeout=30, context=self._context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychromecast/dial.py", line 184, in get_device_info
    _, status = _get_status(
                ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychromecast/dial.py", line 95, in _get_status
    with urllib.request.urlopen(req, timeout=timeout, context=context) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 1313, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1451, in __init__
    super(HTTPSConnection, self).__init__(host, port, timeout,
  File "/usr/local/lib/python3.12/http/client.py", line 878, in __init__
    self._validate_host(self.host)
  File "/usr/local/lib/python3.12/http/client.py", line 1280, in _validate_host
    raise InvalidURL(f"URL can't contain control characters. {host!r} "
http.client.InvalidURL: URL can't contain control characters. 'Lex Fridman' (found at least ' ')
2024-03-31 17:44:25.059 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2024-03-31 17:44:36.463 ERROR (MainThread) [homeassistant.components.homeassistant_alerts] Error requesting homeassistant_alerts data: Cannot connect to host alerts.home-assistant.io:443 ssl:default [Try again]
2024-03-31 17:44:36.524 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2024-03-31 17:44:41.628 ERROR (MainThread) [custom_components.hacs] Could not update plugin - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Try again]
2024-03-31 17:44:41.630 ERROR (MainThread) [custom_components.hacs] Could not update template - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Try again]
2024-03-31 17:44:41.631 ERROR (MainThread) [custom_components.hacs] Could not update integration - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Try again]
2024-03-31 17:44:41.632 ERROR (MainThread) [custom_components.hacs] Could not update theme - Error fetching data from HACS: Cannot connect to host data-v2.hacs.xyz:443 ssl:default [Try again]
2024-03-31 17:44:52.014 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2024-03-31 17:45:17.521 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2024-03-31 17:46:02.617 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2024-03-31 17:47:05.290 WARNING (MainThread) [aioesphomeapi.connection] esp8266 @ 192.168.0.103: Connection error occurred: esp8266 @ 192.168.0.103: Connection requires encryption
2024-03-31 17:47:05.337 WARNING (MainThread) [aioesphomeapi.connection] esp8266 @ 192.168.0.103: Connection error occurred: esp8266 @ 192.168.0.103: Invalid encryption key: received_name=esp8266
2024-03-31 17:47:27.763 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2024-03-31 17:48:32.497 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=36 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=36, family=10, type=2, proto=0, laddr=('::', 44876, 0, 0)>
2024-03-31 17:49:02.501 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:49:32.504 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:49:56.877 ERROR (MainThread) [homeassistant.components.upnp] Error fetching Wireless Router TL-WR741N data: Unable to communicate with IGD at: http://192.168.0.1:1900/igd.xml
2024-03-31 17:49:57.054 WARNING (MainThread) [aioesphomeapi.connection] esp8266 @ 192.168.0.103: Connection error occurred: Ping response not received after 90.0 seconds
2024-03-31 17:49:57.061 WARNING (MainThread) [zeroconf] Error with socket 14 (('192.168.0.100', 5353))): [Errno 101] Network unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1261, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 101] Network unreachable
2024-03-31 17:50:02.507 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:50:05.065 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp8266 @ 192.168.0.103: Error resolving IP address: [Errno -3] Try again (APIConnectionError)
2024-03-31 17:50:32.509 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:51:02.512 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:51:32.515 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:52:02.517 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:52:32.527 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:53:02.529 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:53:32.535 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:54:02.537 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:54:17.031 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=2, type=2, proto=0, laddr=('0.0.0.0', 40806)>
2024-03-31 17:54:32.541 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:55:02.543 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:55:32.547 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:56:02.549 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:56:32.551 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:57:02.554 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:57:32.558 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:58:02.562 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:58:32.565 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:59:02.571 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 17:59:32.574 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:00:02.577 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:00:32.581 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:01:02.585 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:01:32.588 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:02:02.591 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:02:32.593 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:03:02.596 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:03:32.600 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:04:02.603 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:04:17.031 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=2, type=2, proto=0, laddr=('0.0.0.0', 40806)>
2024-03-31 18:04:32.604 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:05:02.607 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:05:32.609 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:06:02.611 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:06:32.616 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:07:02.618 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:07:32.621 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:08:02.623 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:08:32.626 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:09:02.629 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:09:32.633 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:10:02.635 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:10:32.638 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:11:02.644 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:11:32.646 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:12:02.649 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:12:32.651 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:13:02.653 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:13:32.655 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:14:02.658 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:14:17.033 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=2, type=2, proto=0, laddr=('0.0.0.0', 40806)>
2024-03-31 18:14:32.662 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:15:02.664 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:15:32.669 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:16:02.671 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:16:32.674 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:17:02.678 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:17:32.683 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:27:32.721 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:28:02.726 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:28:25.877 ERROR (MainThread) [homeassistant.components.upnp] Error fetching Wireless Router TL-WR741N data: Unable to communicate with IGD at: http://192.168.0.1:1900/igd.xml
2024-03-31 18:28:32.729 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:28:49.311 WARNING (MainThread) [aioesphomeapi.connection] esp32d1mini @ 192.168.0.101: Connection error occurred: Ping response not received after 90.0 seconds
2024-03-31 18:29:02.731 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:29:32.734 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:29:49.319 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32d1mini @ 192.168.0.101: Timeout while connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.0.101', port=6053))] (TimeoutAPIError)
2024-03-31 18:30:02.736 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:30:32.739 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:31:02.741 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:31:32.743 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:32:02.746 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:32:32.753 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:33:02.759 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:33:32.762 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:34:02.766 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:34:17.035 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=2, type=2, proto=0, laddr=('0.0.0.0', 40806)>
2024-03-31 18:34:32.768 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:35:02.770 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:38:25.993 WARNING (MainThread) [aioesphomeapi.connection] esp32c3-supermini @ 192.168.0.104: Connection error occurred: [Errno 104] Connection reset by peer
2024-03-31 18:39:02.787 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:39:32.790 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:40:01.875 ERROR (MainThread) [homeassistant.components.upnp] Error fetching Wireless Router TL-WR741N data: Unable to communicate with IGD at: http://192.168.0.1:1900/igd.xml
2024-03-31 18:40:02.793 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:40:13.616 WARNING (MainThread) [aioesphomeapi.connection] esp32d1mini @ 192.168.0.101: Connection error occurred: Ping response not received after 90.0 seconds
2024-03-31 18:40:32.795 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:40:36.099 WARNING (MainThread) [aioesphomeapi.connection] esp32c3-supermini @ 192.168.0.104: Connection error occurred: Ping response not received after 90.0 seconds
2024-03-31 18:41:02.798 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:41:13.659 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32d1mini @ 192.168.0.101: Timeout while connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.0.101', port=6053))] (TimeoutAPIError)
2024-03-31 18:41:32.799 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:41:36.144 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32c3-supermini @ 192.168.0.104: Timeout while connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.0.104', port=6053))] (TimeoutAPIError)
2024-03-31 18:42:02.801 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:42:32.806 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:43:02.808 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:43:32.811 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:44:02.813 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:44:17.035 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=2, type=2, proto=0, laddr=('0.0.0.0', 40806)>
2024-03-31 18:44:32.816 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:45:02.818 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:45:32.820 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:46:02.823 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:46:32.827 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:47:02.830 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:47:32.833 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:48:02.836 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:48:32.838 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:49:02.840 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:49:32.843 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:50:02.847 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:50:32.849 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:51:02.850 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:51:32.852 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:52:02.855 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:52:32.859 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:53:02.862 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:53:32.864 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:54:02.866 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:54:17.037 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=2, type=2, proto=0, laddr=('0.0.0.0', 40806)>
2024-03-31 18:54:32.868 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:55:02.871 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:55:32.874 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:56:02.877 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:56:32.879 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:57:02.881 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:57:32.884 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:58:02.889 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:58:32.891 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:59:02.894 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 18:59:32.896 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:03:09.173 WARNING (MainThread) [aioesphomeapi.connection] esp32d1mini @ 192.168.0.101: Connection error occurred: [Errno 104] Connection reset by peer
2024-03-31 19:05:19.304 WARNING (MainThread) [aioesphomeapi.connection] esp32d1mini @ 192.168.0.101: Connection error occurred: Ping response not received after 90.0 seconds
2024-03-31 19:05:22.366 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32d1mini @ 192.168.0.101: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.0.101', port=6053))]: [Errno 113] Connect call failed ('192.168.0.101', 6053) (SocketAPIError)
2024-03-31 19:06:02.917 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:06:02.925 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 99] Address not available, transport: <_SelectorDatagramTransport fd=36 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=36, family=10, type=2, proto=0, laddr=('::', 44876, 0, 0)>
2024-03-31 19:06:32.921 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:07:02.924 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:07:22.877 ERROR (MainThread) [homeassistant.components.upnp] Error fetching Wireless Router TL-WR741N data: Unable to communicate with IGD at: http://192.168.0.1:1900/igd.xml
2024-03-31 19:07:32.927 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:07:59.352 WARNING (MainThread) [aioesphomeapi.connection] esp8266 @ 192.168.0.103: Connection error occurred: Ping response not received after 90.0 seconds
2024-03-31 19:08:02.930 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:08:03.216 WARNING (MainThread) [aioesphomeapi.connection] esp32c3-supermini @ 192.168.0.104: Connection error occurred: Ping response not received after 90.0 seconds
2024-03-31 19:08:07.401 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp8266 @ 192.168.0.103: Error resolving IP address: [Errno -3] Try again (APIConnectionError)
2024-03-31 19:08:32.932 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:09:02.935 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:09:03.222 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32c3-supermini @ 192.168.0.104: Timeout while connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.0.104', port=6053))] (TimeoutAPIError)
2024-03-31 19:09:32.937 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:10:02.940 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:10:32.942 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:11:02.944 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:11:32.947 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:12:02.949 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:12:32.962 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:13:46.990 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:14:19.909 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:14:19.975 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=2, type=2, proto=0, laddr=('0.0.0.0', 40806)>
2024-03-31 19:14:49.975 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:15:19.978 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:15:49.979 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:16:19.982 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:16:49.984 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:17:19.986 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:17:49.989 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:18:19.993 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:18:49.996 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:19:19.999 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:19:50.003 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:20:20.007 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:20:50.008 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:21:20.010 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:21:50.014 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:22:20.017 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:22:50.020 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:23:20.024 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:23:50.027 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:24:19.780 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=2, type=2, proto=0, laddr=('0.0.0.0', 40806)>
2024-03-31 19:24:20.030 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:24:50.032 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:25:20.036 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:25:50.039 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:26:20.043 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:26:50.047 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:27:20.051 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:27:50.055 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
2024-03-31 19:28:20.058 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=32 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=32, family=2, type=2, proto=0, laddr=('0.0.0.0', 54459)>
